spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092
  cloud:
    openfeign:
      client:
        config:
            test:
                url: http://remote-service.com
                connectTimeout: 5000
                readTimeout: 5000
                loggerLevel: full
      httpclient:
        hc5:
          enabled: true

tpd:
  topic-name: advice-topic
  messages-per-request: 10

#pybc:
#  urlMap:
#    pay: https://randomuser.me
#    memb: https://randomuser.me

prop:
  test:
    test1:
      name: test1
      value: value1
    test2:
      name: test2
      value: value2

multiple-datasource:
  test: test
  datasource-config:
    - name: datasourceOne
      datasource:
        jdbcUrl: jdbc:h2:file:d:/test_db;AUTO_SERVER=TRUE
        username: test
        password: test
        driverClassName: org.h2.Driver
        maximumPoolSize: 20
      mybatis:
        config-location:
        mapper-locations: classpath*:/mapper/**/*.xml
        base-package: config
        annotation-class: org.apache.ibatis.annotations.Mapper
    - name: datasourceTwo
      datasource:
        jdbcUrl: jdbc:h2:file:d:/test_db;AUTO_SERVER=TRUE
        username: test
        password: test
        driverClassName: org.h2.Driver
        maximumPoolSize: 20
      mybatis:
        config-location:
        mapper-locations: classpath*:/mapper/**/*.xml
        base-package: config
        annotation-class: config.data.TwoMapper
